//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnyHire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int PackageId { get; set; }
        public int Stars { get; set; }
        public bool Disliked { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
    }
}
