//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnyHireAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int Id { get; set; }
        public int NID { get; set; }
        public string Coverage { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string Skills { get; set; }
        public decimal Revenue { get; set; }
        public decimal Commission { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
